### ISSUE TITLE
Split universal and opentype profiles?

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/fontspector#14]

**Comment by felipesanches** [comment]
yes, please ;-)

**Comment by felipesanches** [comment]
@simoncozens, I'll prepare a PR for this one, ok?

**Comment by simoncozens** [comment]
Yes, sure. Thank you!

**Comment by felipesanches** [comment]
Also, please make the adjustments for me to be able to self-assign issues in this repo (or maybe we should migrate it to the fonttools org, just like fontbakery)

**Comment by simoncozens** [comment]
Maybe hold off on this for a moment. I think maybe one of the reasons why I merged universal and opentype profiles is because that split is not correct in fontbakery.

For example: `opentype/name/italic_names` looks at the filename to determine whether the font is Italic or Regular and checks the name table entries accordingly. That's not a matter for the OpenType standard; it's a Universal check, but fontbakery has it on the opentype profile.

**Comment by felipesanches** [comment]
well... then we rename that check to 'name/italic_names' and move it to Universal.
