### ISSUE TITLE
web version at https://googlefonts.github.io/fontspector gives a 404 error 

### ISSUE THREAD

**Issue by mitradranirban** [simoncozens/fontspector#22]
Screenshot attached 
![Screenshot from 2024-11-14 22-47-07](https://github.com/user-attachments/assets/6f20d145-3523-4be5-8aea-b27d721721de)

**Comment by simoncozens** [comment]
Should be https://simoncozens.github.io/fontspector ; I'll fix the readme.

**Comment by simoncozens** [comment]
Done in 81a180f
