### ISSUE TITLE
remove "proposal=legacy" syntax

### ISSUE THREAD

**Issue by felipesanches** [simoncozens/fontspector#24]
In the past I had set the proposal field of a few very old checks (in the fontbakery codebase) with a special "legacy:check-number" syntax to indicate that we lack a good description of an original proposal,  but at least we know which check was this based on (from a time when we used numbers instead of words in check-IDs).

Recently I opened an issue with a summary list of these old checks, so that we can simply reference that URL, instead of using that custom syntax. This will make it easier to parse the proposal field when displaying its contents on documentation and on the reporters.

This is the PR that contains the changes that should be also ported to fontspector:
https://github.com/fonttools/fontbakery/pull/4830

**Comment by simoncozens** [comment]
I think we're using `"https://github.com/fonttools/fontbakery/issues/4829",  // legacy check` for all legacy checks in fontspector.
