### ISSUE TITLE
--list-checks doesn’t show the google checks

### ISSUE THREAD

**Issue by schriftgestalt** [simoncozens/fontspector#27]
Is that on purpose? The web-version has a google check option.

**Comment by simoncozens** [comment]
Like fontbakery, fontspector has the concept of profiles. `--list-checks` on its own will list the checks in the default profile, `universal`. To change profile, use `--profile googlefonts`.

**Comment by schriftgestalt** [comment]
The output looks like that is shows the check for the OpenType and for the Universal profile. So I thought that this were the two produces. Thanks for the explanation.
